JJOEC/Controllers/JJPlotController.cs
/* 
 * Assignment2: MVC: Persistence
 *
 * Revision History
 *       Jay Jang, 2017.9.25: Created
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JJOEC.Models;
using Microsoft.AspNetCore.Http;

namespace JJOEC.Controllers
{
    public class JJPlotController : Controller
    {
        private readonly OECContext _context;

        public JJPlotController(OECContext context)
        {
            _context = context;
        }

        // GET: JJPlot
        public async Task<IActionResult> Index(int? cropId, string cropName, string farmName,
            int? varietyId, string varietyName, int? plotId, string orderType, string identifyCriteria)
        {
            if (identifyCriteria == "T")
            {
                if (plotId != null)
                {
                    HttpContext.Session.SetString(nameof(plotId), plotId.ToString());
                }
                else
                {
                    plotId = Convert.ToInt32(HttpContext.Session.GetString(nameof(plotId)));
                }
                var kMOECContext = _context.Plot.Where(a => a.PlotId == plotId)
                    .Include(p => p.Farm)
                    .Include(p => p.Variety)
                    .Include(p => p.Variety.Crop)
                    .Include(p => p.Treatment);
                return View(await kMOECContext.ToListAsync());
            }
            else if (identifyCriteria == "V") // From Variety
            {
                if (varietyId != null)
                {
                    HttpContext.Session.SetString(nameof(varietyId), varietyId.ToString());
                    HttpContext.Session.SetString("varietyName", varietyName);
                }
                else if (HttpContext.Session.GetString(nameof(varietyId)) != null)
                {
                    varietyId = Convert.ToInt32(HttpContext.Session.GetString(nameof(varietyId)));
                    varietyName = HttpContext.Session.GetString(nameof(varietyName));
                }
                else
                {
                    TempData["message"] = "Select a variety to see its plots.";
                    return RedirectToAction("Index", "JJVariety");
                }

                //The farm, variety and CEC into hyperlinks that reorder the listing by that field.
                if (orderType == "Farm")
                {
                    var oECContext = _context.Plot.Where(a => a.VarietyId == varietyId)
                        .OrderBy(a => a.Farm.Name).Include(p => p.Farm)
                        .Include(p => p.Variety).Include(p => p.Variety.Crop)
                        .Include(p => p.Treatment);
                    return View(await oECContext.ToListAsync());
                }
                else if (orderType == "Variety")
                {
                    var oECContext = _context.Plot.Where(a => a.VarietyId == varietyId)
                        .OrderBy(a => a.Variety.Name).Include(p => p.Farm)
                        .Include(p => p.Variety).Include(p => p.Variety.Crop)
                        .Include(p => p.Treatment);
                    return View(await oECContext.ToListAsync());
                }
                else if (orderType == "CEC")
                {
                    var oECContext = _context.Plot.Where(a => a.VarietyId == varietyId)
                        .OrderBy(a => a.Cec).Include(p => p.Farm)
                        .Include(p => p.Variety).Include(p => p.Variety.Crop)
                        .Include(p => p.Treatment);
                    return View(await oECContext.ToListAsync());
                }
                else //default
                {
                    var oECContext = _context.Plot.Where(a => a.VarietyId == varietyId)
                        .OrderBy(a => a.DatePlanted).Include(p => p.Farm)
                        .Include(p => p.Variety).Include(p => p.Variety.Crop)
                        .Include(p => p.Treatment);
                    return View(await oECContext.ToListAsync());
                }
            }
            else if(identifyCriteria =="C") // From Crop
            {
                if (cropId != null) 
                {
                    HttpContext.Session.SetString(nameof(cropId), cropId.ToString());
                    HttpContext.Session.SetString("cropName", cropName);
                }
                else if (HttpContext.Session.GetString(nameof(cropId)) != null)
                {
                    cropId = Convert.ToInt32(HttpContext.Session.GetString(nameof(cropId)));
                    cropName = HttpContext.Session.GetString(nameof(cropName));
                }
                else
                {
                    TempData["message"] = "Select a crop to see its plots.";
                    return RedirectToAction("Index", "JJCrop");
                }

                //The farm, variety and CEC into hyperlinks that reorder the listing by that field.
                if (orderType == "Farm")
                {
                    var kMOECContext = _context.Plot.Where(a => a.Variety.Crop.CropId == cropId)
                        .OrderBy(a => a.Farm.Name)
                        .Include(p => p.Farm)
                        .Include(p => p.Variety)
                        .Include(p => p.Variety.Crop)
                        .Include(p => p.Treatment);
                    return View(await kMOECContext.ToListAsync());
                }
                else if (orderType == "Variety")
                {
                    var oECContext = _context.Plot.Where(a => a.Variety.Crop.CropId == cropId)
                        .OrderBy(a => a.Variety.Name)
                        .Include(p => p.Farm)
                        .Include(p => p.Variety)
                        .Include(p => p.Variety.Crop)
                        .Include(p => p.Treatment);
                    return View(await oECContext.ToListAsync());
                }
                else if (orderType == "CEC")
                {
                    var oECContext = _context.Plot.Where(a => a.Variety.Crop.CropId == cropId)
                        .OrderBy(a => a.Cec).Include(p => p.Farm)
                        .Include(p => p.Variety)
                        .Include(p => p.Variety.Crop)
                        .Include(p => p.Treatment);
                    return View(await oECContext.ToListAsync());
                }
                else
                {
                    var kMOECContext = _context.Plot.Where(a => a.Variety.Crop.CropId == cropId)
                        .Include(p => p.Farm)
                        .Include(p => p.Variety)
                        .Include(p => p.Variety.Crop)
                        .Include(p => p.Treatment);
                    return View(await kMOECContext.ToListAsync());
                }
            }
            else //default All plots on file
            {
                var kMOECContext = _context.Plot
                .Include(p => p.Farm)
                .Include(p => p.Variety)
                .Include(p => p.Variety.Crop)
                .Include(p => p.Treatment);
                return View(await kMOECContext.ToListAsync());
            }
        }

        // GET: JJPlot/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plot = await _context.Plot
                .Include(p => p.Farm)
                .Include(p => p.Variety)
                .SingleOrDefaultAsync(m => m.PlotId == id);
            if (plot == null)
            {
                return NotFound();
            }

            return View(plot);
        }

        // GET: JJPlot/Create
        public IActionResult Create()
        {
            ViewData["FarmId"] = new SelectList(_context.Farm, "FarmId", "Name"); //display by Name
            ViewData["VarietyId"] = new SelectList(_context.Variety
                .Where(a => a.CropId == Convert.ToInt32(HttpContext.Session.GetString("cropId"))), "VarietyId", "Name"); //display by Name
            return View();
        }

        // POST: JJPlot/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PlotId,FarmId,VarietyId,DatePlanted,DateHarvested,PlantingRate,PlantingRateByPounds,RowWidth,PatternRepeats,OrganicMatter,BicarbP,Potassium,Magnesium,Calcium,PHsoil,PHbuffer,Cec,PercentBaseSaturationK,PercentBaseSaturationMg,PercentBaseSaturationCa,PercentBaseSaturationH,Comments")] Plot plot)
        {
            if (ModelState.IsValid)
            {
                _context.Add(plot);
                await _context.SaveChangesAsync();
                if (HttpContext.Session.GetString("varietyId") != null)
                {
                    return RedirectToAction(nameof(Index), new { varietyId = HttpContext.Session.GetString("varietyId"), varietyName = HttpContext.Session.GetString("varietyName") });
                }
                else
                {
                    return RedirectToAction(nameof(Index), new { cropId = HttpContext.Session.GetString("cropId"), cropName = HttpContext.Session.GetString("cropName") });
                }
            }
            ViewData["FarmId"] = new SelectList(_context.Farm, "FarmId", "Name", plot.FarmId);
            ViewData["VarietyId"] = new SelectList(_context.Variety, "VarietyId", "Name", plot.VarietyId);
            return View(plot);
        }

        // GET: JJPlot/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {

JJOEC/Controllers/JJVarietyController.cs
/* 
 * Assignment2: MVC: Persistence
 *
 * Revision History
 *       Jay Jang, 2017.9.25: Created
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JJOEC.Models;
using Microsoft.AspNetCore.Http;

namespace JJOEC.Controllers
{
    public class JJVarietyController : Controller
    {
        private readonly OECContext _context;

        public JJVarietyController(OECContext context)
        {
            _context = context;
        }

        // GET: JJVariety
        public async Task<IActionResult> Index(int? cropId, string cropName)
        {
            if (cropId != null) // if not, error
            {
                HttpContext.Session.SetString(nameof(cropId), cropId.ToString());
                HttpContext.Session.SetString(nameof(cropName), cropName);
            }
            else if (HttpContext.Session.GetString(nameof(cropId)) != null)
            {
                cropId = Convert.ToInt32(HttpContext.Session.GetString(nameof(cropId)));
                cropName = HttpContext.Session.GetString(nameof(cropName));
            }
            else
            {
                TempData["message"] = "Select a crop to see its varieties";
                return RedirectToAction("Index", "JJCrop");
            }

            //Order By Variety name
            var oECContext = _context.Variety.Where(a => a.CropId == cropId).OrderBy(a => a.Name).Include(v => v.Crop);
            return View(await oECContext.ToListAsync());
        }

        // GET: JJVariety/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var variety = await _context.Variety
                .Include(v => v.Crop)
                .SingleOrDefaultAsync(m => m.VarietyId == id);
            if (variety == null)
            {
                return NotFound();
            }

            return View(variety);
        }

        // GET: JJVariety/Create
        public IActionResult Create()
        {
            ViewData["CropId"] = new SelectList(_context.Crop, "CropId", "CropId");
            return View();
        }

        // POST: JJVariety/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VarietyId,CropId,Name")] Variety variety)
        {
            if (ModelState.IsValid)
            {
                _context.Add(variety);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CropId"] = new SelectList(_context.Crop, "CropId", "CropId", variety.CropId);
            return View(variety);
        }

        // GET: JJVariety/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var variety = await _context.Variety.SingleOrDefaultAsync(m => m.VarietyId == id);
            if (variety == null)
            {
                return NotFound();
            }
            ViewData["CropId"] = new SelectList(_context.Crop, "CropId", "CropId", variety.CropId);
            return View(variety);
        }

        // POST: JJVariety/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VarietyId,CropId,Name")] Variety variety)
        {
            if (id != variety.VarietyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(variety);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VarietyExists(variety.VarietyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CropId"] = new SelectList(_context.Crop, "CropId", "CropId", variety.CropId);
            return View(variety);
        }

        // GET: JJVariety/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var variety = await _context.Variety
                .Include(v => v.Crop)
                .SingleOrDefaultAsync(m => m.VarietyId == id);
            if (variety == null)
            {
                return NotFound();
            }

            return View(variety);
        }

        // POST: JJVariety/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var variety = await _context.Variety.SingleOrDefaultAsync(m => m.VarietyId == id);
            _context.Variety.Remove(variety);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VarietyExists(int id)
        {
            return _context.Variety.Any(e => e.VarietyId == id);
        }
    }
}

JJOEC/Views/JJVariety/Create.cshtml
@model JJOEC.Models.Variety
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = $"Create Varieties of {Context.Session.GetString("cropName")}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewData["Title"]</h2>

<h4>Variety</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" name="CropId" value=@Context.Session.GetString("cropId") />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JJOEC/Views/JJVariety/Delete.cshtml
@model JJOEC.Models.Variety
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = $"Delete {Model.Name}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewData["Title"]</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Variety</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Crop)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Crop.CropId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="VarietyId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

JJOEC/Views/JJVariety/Details.cshtml
@model JJOEC.Models.Variety
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = $"{Model.Name} Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewData["Title"]</h2>

<div>
    <h4>Variety</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Crop)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Crop.CropId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.VarietyId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

JJOEC/Views/JJVariety/Edit.cshtml
@model JJOEC.Models.Variety
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = $"Edit {Model.Name}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewData["Title"]</h2>

<h4>Variety</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <input type="hidden" asp-for="VarietyId" />
            <input type="hidden" name="cropId" value=@Context.Session.GetString("cropId") />

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JJOEC/Views/JJVariety/Index.cshtml
@model IEnumerable<JJOEC.Models.Variety>
@using Microsoft.AspNetCore.Http

@{
    ViewData["Title"] = $"Varieties of {Context.Session.GetString("cropName")}";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewData["Title"]</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-action="Index" asp-controller="JJPlot" asp-route-identifyCriteria="V" asp-route-varietyId="@item.VarietyId" asp-route-varietyName="@item.Name">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.VarietyId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.VarietyId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.VarietyId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>